name: Integration Test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "iac/**"
      - ".github/workflows/integration-test.yml"

permissions:
  contents: read

jobs:
  tofu-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Tofu
        uses: opentofu/setup-opentofu@v1

      - name: Initialize Tofu
        run: tofu init

      - name: Run Tofu Plan
        id: plan
        run: |
          tofu plan -detailed-exitcode -no-color > plan.txt
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check for changes
        run: |
          if [ "${{ steps.plan.outcome }}" != "success" ]; then
            echo "Tofu plan detected changes or failed."
            cat plan.txt
            exit 1
          fi
        shell: bash
